os: linux
language: c
sudo: false

before_script:
  - mkdir -p bin
  - curl -sL `curl -s https://api.github.com/repos/tcnksm/ghr/releases/latest | jq -r '.assets[] | select(.name | test("linux_amd64.tar.gz"; "ix")) | .browser_download_url'` | tar -xz -C bin

script:
  - make

branches:
  only:
    - master
    - /^v\d+\.\d+.\d+$/

notifications:
  email:
    on_success: false
    on_failure: always

deploy:
  provider: script
  script:
  - make deploy
  on:
    branch: master
    # tags: true
