os: linux
language: c
sudo: false

script:
  - make

branches:
  only:
    - master
    - /^v\d+\.\d+.\d+$/

notifications:
  email:
    on_success: false
    on_failure: always

before_deploy:
  - ./.ci/install.sh

deploy:
  provider: script
  script:
  - make deploy
  on:
    branch: master
    # tags: true
