#!/bin/sh
set -e

SRC=$1
USR=$2
REP=$3

URI=https://${GITHUB_PERSONAL_ACCESS_TOKEN}@github.com/${REP}.git

DST=.tmp

rm -rf $DST
git clone --no-checkout $URI $DST

cd $DST
if [ "`git branch -a | grep gh-pages`" != "" ]; then
git checkout gh-pages
else
git checkout --orphan gh-pages
fi
cd -

cp -r $SRC/ $DST

cd $DST
git add --all
git commit -m "deploy"
git push $URI
cd -

rm -rf $DST