#!/bin/bash
set -e

: "${AWS_ACCESS_KEY_ID:?AWS_ACCESS_KEY_ID is mising}"
: "${AWS_SECRET_ACCESS_KEY:?AWS_SECRET_ACCESS_KEY is mising}"

SRC=$1
BCK=$2

BASE=$(dirname $0)
source $BASE/env.sh

aws s3 sync $SRC/ s3://${BCK}/

# aws s3 cp --recursive $SRC/ s3://${BCK}/

# s3cmd put --recursive \
#   --access_key=$AWS_ACCESS_KEY_ID \
#   --secret_key=$AWS_SECRET_ACCESS_KEY \
#   $SRC/ \
#   s3://${BCK}/

