#!/bin/bash
set -e

BASE=$(dirname $0)
source $BASE/env.sh

SRC=$1
URI=$2

DST=.tmp

rm -rf $DST
git clone --quiet $URI $DST
cp -r $SRC/ $DST
cd $DST
git add --all
git commit -m "CI deployment"
git push --quiet $URI
cd - > /dev/null
rm -rf $DST