#!/bin/bash
set -e

SRC=$1
REP=$2

URI=git@github.com:${REP}.git
BASE=$(dirname $0)
source $BASE/env.sh
DST=.tmp

rm -rf $DST
git clone --quiet --no-checkout $URI $DST

cd $DST
if [ "`git branch -a | grep gh-pages`" != "" ]; then
git checkout --quiet gh-pages
else
git checkout --quiet --orphan gh-pages
fi
cd -

cp -r $SRC/ $DST

cd $DST
git add --all
git commit -m "deploy"
git push --quiet $URI
cd -

rm -rf $DST