#!/bin/bash
set -e

BASE=$(dirname $0)
source $BASE/env.sh

SRC=$1
URI=$2
BRANCH=gh-pages

DST=.tmp

rm -rf $DST
git clone --quiet --no-checkout $URI $DST

cd $DST
if [ "`git branch -a | grep $BRANCH`" != "" ]; then
git checkout --quiet $BRANCH
else
git checkout --quiet --orphan $BRANCH
fi
cd - > /dev/null

cp -r $SRC/ $DST

cd $DST
git add --all
git commit -m "CI deployment"
git push --quiet $URI
cd - > /dev/null

rm -rf $DST