#!/bin/sh

echo "github"



# hugo
# git add -A
# msg="rebuilding site `date`"
# if [ $# -eq 1 ]
#   then msg="$1"
# fi
# git commit -m "$msg"

# git push origin master
# git subtree push --prefix=public git@github.com:spencerlyon2/hugo_gh_blog.git gh-pages
